# -*- coding: utf-8 -*-
"""Assesment 2

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13t-8hpkcsJLkQbUG2KK3A49oBaH16nTC
"""

#menu 
menu = [
    {"code":1, 
     "name":'OREO',
     "price":3},

    {"code":2,
     "name":'TWIX' ,
     "price":2},

    {"code":3,
     "name":'KITKAT',
     "price":3},

    {"code":4,
     "name": 'GUM',
     "price":1},

    {"code":5,
     "name": 'PEPSI',
     "price":3},

    {"code":6,
     "name": 'COKE',
     "price":3},

    {"code":7,
     "name": 'SPRITE',
     "price":3},

    {"code":8,
     "name": '7UP',
     "price":3}
    ]

def food(): #displays a message by welcoming the user
  print('\t**\t WELCOME TO RISE VENDING MACHINE \t**')
  print('        *    * BELOW IS THE GIVEN MENU *        *')
  

  menu = {
    "1 Oreo" : "3 AED", 
    "2 TWIX" : "2 AED",
    "3 KITKAT" : "3 AED",
    "4 GUM" : "1 AED",
    "5 PEPSI" : "3 AED",
    "6 COKE" : "3 AED",
    "7 SPRITE" : "3 AED",
    "8 7UP" : "3 AED"

   }

  for item, price in menu.items():
    print(f" {item:10}, {price}")
  print() #it prints out the dictionary like a menu


def place_order(): #this is  defining the place order system
   
   while True: #starts the operation using a while loop

     food()
     #asks the user to enter their amount
     print('=======================================\n')
     AED= int(input('Enter your Amount: '))
     print('=======================================\n')
     if AED <= 0:# If the amount is less than 0 it prints a message saying inavlid amount
       print('=======================================\n')
       print('YOU HAVE NOT ENTERED A VALID AMOUNT...Please enter a valid amount')
       print('=======================================\n')
       print(' YOU HAVE ENTERED ,', AED)# displays a message saying you have entered ... AED

      
     for z in menu:
     #asks the user to pick the item
      item_choice= int(input("Choose your desired choice  :"))
      if item_choice <=0 or item_choice >=8 : #if the user inputs an item more than 8 or less than 1 it shows a message 'INVALID CODE'
         print('INVALID ITEM CODE... Pleased enter a valid item code')

      if item_choice == z['code'] and AED <= z['price']:
          print('=======================================\n')
          print('YOU DONT HAVE ENOUGH AED TO BUY THIS PRDUCT')
          print('=======================================\n')
      elif item_choice == z['code'] and AED >= z['price']:

          #displays the item the user picked
          print('=======================================\n')
          print(f"You picked {z['name']}\n")
          
          print('=======================================\n')
          print("You will now recieve your item through the dispense tray\n")#dispenses the desired item using the tray
         

          print('=======================================\n')
          print("Thank you for using RISE VENDING MACHINE :)1\n") #displays a message to the user saying THANK YOU
          print('=======================================\n')

     break
    
place_order()